# Generated by Django 5.2.7 on 2025-10-22 09:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=10)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_assignment.contributor')),
            ],
            options={
                'db_table': 'attendance',
                'unique_together': {('contributor', 'date')},
            },
        ),
    ]
